doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid_type: \App\Common\UUIDType
            bonus_salary_policy_type: \App\Payroll\Infrastructure\Doctrine\BonusSalaryPolicyType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AppDepartment:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Department/Infrastructure/Doctrine'
                type: xml
                prefix: 'App\Department\Domain'
                alias: AppDepartment
            AppPayroll:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Payroll/Infrastructure/Doctrine'
                type: xml
                prefix: 'App\Payroll\Domain'
                alias: AppPayroll

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
