framework:
    messenger:
        default_bus: event.bus

        transports:

        routing:
            # Route your messages to the transports
        buses:
          event.bus:
            default_middleware: allow_no_handlers

