services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "composer install"
    working_dir: /app
    volumes:
      - .:/app:cached
    depends_on:
      - database

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
